# fly.toml app configuration file generated for kubeversion-api-v1 on 2023-05-15T12:16:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kubeversion-api-v1"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
